# Generated by Django 4.2.5 on 2023-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('otp', models.IntegerField(max_length=6)),
                ('validity', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
