# Generated by Django 4.2.5 on 2023-10-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='validity',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
